---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: monitoring
spec:
  storageClassName: local-path
  # storageClassName: nfsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
