---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.26.5
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
    adminUser: admin
    adminPassword: "${SECRET_GRAFANA_PASSWORD}"
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_PUBLIC_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
    deploymentStrategy:
      type: RollingUpdate
    image:
      repository: grafana/grafana
      tag: 8.3.6
      sha: ""
      pullPolicy: IfNotPresent
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 3000
        # targetPort: 4181 To be used with a proxy extraContainer
      portName: service
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - "grafana.ninhu.xyz"
      tls:
        - secretName: grafana-tls
          hosts:
            - "grafana.ninhu.xyz"
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        # list of datasources that should be deleted from the database
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://192.168.37.216:9090
            isDefault: true
          - name: Prometheus-1
            type: prometheus
            access: proxy
            url: http://192.168.37.220:9090

    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/7845
        #zfs:
        #  gnetId: 7845
        #  revision: 4
        #  datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/14282
        cadvisor:
          gnetId: 14282
          revision: 1
          datasourse: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/1860
        node-exporter-full:
          gnetId: 1860
          revision: 26
          datasource: Prometheus-1
        # Ref: https://grafana.com/grafana/dashboards/4475
        traefik:
          gnetId: 4475
          revision: 5
          datasource: Prometheus-1
        ceph-cluster:
          gnetId: 2842
          revision: 14
          datasource: Prometheus-1
        # Ref: https://grafana.com/grafana/dashboards/5336
        ceph-osd:
          gnetId: 5336
          revision: 5
          datasource: Prometheus-1
        ## Ref: https://grafana.com/grafana/dashboards/5342
        ceph-pools:
          gnetId: 5342
          revision: 5
          datasource: Prometheus-1
        speedtest:
          gnetId: 13665
          revision: 1
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus-1
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus-1
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    serviceMonitor:
      enabled: true
      create: true
      autoMount: true
    serviceAccount:
      create: true
      autoMount: true
    persistence:
      enabled: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"
