# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nQ0ePL/wgSFojxD1JODb7hFs2gQ=,iv:9ot3NodQTLZ7zqfphea0yQDvSYumusXJ3He0PJFDSWc=,tag:K4x1Mws7/UVwZqofUl1RGA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+cttnKGOEmOZctc18Cby76z9yC8weopS0h3jmkfo8Xmm2cCXIg==,iv:sziyT32tubbAquGsjvgHA6iQholtIaSSpr8RwqBTuUU=,tag:kNzyiILWW5rvO+HXJi1wdw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vwiBL21KqTQ9RMvIs+c=,iv:HF0PKzV4X1d9PVFOUAtIbrMQf0LpfFxwWCamw6r+abs=,tag:Kg6Xrwop354OZTPEMxUJ9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZnJKWTBSY0lzRW43WkZs
            aWdkNG52NkxNc2h4VkJZcUdhWUZPTmlrZlFnCkR6Ym9BQnpZNWFhS0FkengyWGY0
            K1NvTDQ1WkQ0RTVQRVJwREdVTGVITTAKLS0tIFAxYXFieFZYNUVIc29IdDhNUndv
            dzJ2SkVEdmtTT1lmUkxlQzZxcXI3TjQKocQ4L4oz03xyEDySos5XsXuiI89u6Hc8
            atu04lVnvnMcrEaSrMIZROhNZt57WjsG1pZ18gg7cktU0UdbP+mDmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-24T00:43:19Z"
    mac: ENC[AES256_GCM,data:ns7rG7ya3pCHf9/FiRUt+Z3yEty3C2MIGw/pmnXYJYcXp0dRykqZ1WvRF8q9hZR5qymQmDutEtekuNmL7l1py/wUyflHtqpGtmyg0JdX1lkLDeU67bLfQPjE5whLmY+7bbhdXAJ7CbNpdY7wv5DlAZyeaOO9rSVIn6IAVvUQipA=,iv:Tx3l+DyPM/sPoqQe6MjMUord8l1PihvHh39U/SfaxGQ=,tag:dt4K3M8puX0xdARVPV9ifw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
