# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2bKzKXc4SU0wzpqu+oln+4xjQDI=,iv:oLNavpUrJkgUs+Bq/ATTwJiqQgZjqbP/1rfNZDBqY1E=,tag:zqoIf/VHFA4ORABYoTnScA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Yaup/P+GARJj3oKdRELvb6rcBRVREBGRq7DIXwd+ffsf5LoO4A==,iv:wwCExDay6TZ5thWJTOsDhhhVrksm65EV5R7tY92lnh8=,tag:vG9zFA8BeoaE531/mG86Cg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:GUCSAlsW0ydWITwZNDY=,iv:KAyE/qtW2qJxYfs7ozI5dUPuP6hjGDMp+HFLBUFjLqs=,tag:xlEaeyDfvs7K5vES5lMyjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeEszWlRYZml1MG54WStH
            MjBTeGg4Q3FFaDJIekxCU2NqNmFHVUhlVkZVCmgrNW1aQlBqSXFBT2F3YnVMOTJ6
            SDVDWFZ6NERtMytvZjdmYU0yL2dOdEEKLS0tIERLZHVjczNCMTlldnhja29SampS
            Nis5L3p6YmxaaEhXS1dPQXVjSFhTbW8K7oM7cSXBzA9rWga/2V0L+sLiQTsuWkSd
            sGu1dfAL5UhBRHeLRvGRwao+p5vesOnwA4VIPMboF1i/gNJDBLdHzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-20T21:16:41Z"
    mac: ENC[AES256_GCM,data:YDhdbWcsDUPqQijYEVv9pHJj7pMM2xiAsnr8ehBvVP/EwaonfVdTFLqw97PZka2pZlTlmIlSGVEJU2fTHkZ878wtHvk+iNwZChyrpxddulXGczdYNJtvm3M9LlqULtRw6Hc3mSJvoaNX6Psr8arRs1xWDt2Hch5+2o1ReeFfOH8=,iv:jhF1s/g3fgzLbk4jJooFLyVp/Drvrt9hzUWaOPCxAeQ=,tag:S3IGj9e+4WetD04d8pN2/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
