---
kubernetes:
  children:
    master:
      hosts:
        home-opsm0:
          ansible_host: 192.168.122.120
        home-opsm1:
          ansible_host: 192.168.122.121
    worker:
      hosts:
        home-opsw1:
          ansible_host: 192.168.122.122
