---
kubernetes:
  children:
    master:
      hosts:
        home-opsm0:
          ansible_host: 192.168.37.120
        home-opsm1:
          ansible_host: 192.168.37.121
        home-opsm2:
          ansible_host: 192.168.37.122
    worker:
      hosts:
        home-opsw1:
          ansible_host: 192.168.37.123
        home-opsw2:
          ansible_host: 192.168.37.124
