kind: Secret
ansible_user: ENC[AES256_GCM,data:zEMDRqz+Ezw=,iv:82q3qICP+fNsQc50+1YjcZbzvl6V7Te7NyRyofLmQYk=,tag:Sa1EsydFwwCEDOnHb5/bew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qCNuWPdbgNoNfLqzmbc=,iv:yF8doZAfdFxdyO0VMRYasAfWjByTnBcLdd0yW9CWkSc=,tag:f+JumV+qZ+u+zvOMG+WTiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WW1lNTJ1VVljNG9GRm1X
            YkV3UkprSXRwaUMrSURVbWl0dXFtdk02NFYwCkdmU21UVy8yUnU1aWVoZ3V2OWEv
            MSs3U3JSdmtWaGdUa3hxYnFReFkwTjgKLS0tIExoZnQ5QkhTUWI3MGNnRk0wQlZx
            QTBCZ1lycU5sbUxKclhmY05xYURLVGMK1wULLUsOra9oyDNz1H4ibJRBpgYr2Ix4
            v2n3QQIYIIvTTifXPgfJ2kZ1kXqE5N8w3j8MYwbVv1Frlg/hySBFKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-24T00:43:19Z"
    mac: ENC[AES256_GCM,data:NPEPNNitX9mogWbo9e+kAm8Jzb5QVLhGMKY26pNYz9/Pv/qfVuLHV8kIORB8ot4vvodFj69fTjzQbVLe9u5XiL+fVkJqLnt9gD1RyUJ8koy3hHOu0lyXJGTzRbIyAWrliuRXcoEnhg5YCc9ZBM2b2THTs3XOmkZB02QxKWnPBLw=,iv:yhleBolZKEG74ZgFbfzasHKyYL/w5dpO23qZgPeYjSY=,tag:JkdeIfh6eRZ6QmH/XZjU6w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
