kind: Secret
ansible_user: ENC[AES256_GCM,data:S4cpZvXdjm0=,iv:pfGr82u+aQzTM2SJN1nZS933Zec/1vCjygcILpMtmK4=,tag:Jw0wvV9hITdDHJPo0+Qneg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:a8wjyz2dHtmMPpS8RoM=,iv:+VDuE9n4MP5cJwh77Uth9BkonMHaDbvTmnCdRz5f5+Y=,tag:3mRrFy8Sqewzmbng8e05qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZVRvTDJHVGRLMGpLSkJj
            d2xOVTJ5NFVrWkpSb080L1FQb296OVVwT25ZCmtEcE05TytrMS9Lbmh2SWdmaWk0
            MnhhMkVRTVJEVXRFeEdmQ1hyaXRLQ1EKLS0tIElTWlBBcnlkRklNbVNFTXZmREZI
            SmRUQW1vaW9FLzg0Ymx0bFVVWGNiTTgK+227luYv47oo1UThhm6WbgqzYRIMNK2b
            GZKu2KtEYCzpzckPtHcNGid0+mWrrwllzBjSowXCTwmXtBvsr6J6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-20T21:16:41Z"
    mac: ENC[AES256_GCM,data:OQp6DPdgWTkKH7oFufq0LGVR5cmZsWrJGvzxU6xX1gPKTFXDm94EeLDIsGi8tZk/ZyjyxqeqHkJpLYa7vp/15IzkIxPn8h23kv9oylrHtxQxNXYJbwLAO2H8lX/djxfv9qxB/NiwZVSZbDiNo1Q8oFb0GEuS2S8pDtTgLEFykas=,iv:oPMQWfBUmrp+srsQ3Z8ibuVhr+f9iIdML2KUBKnNlJo=,tag:gF4J0p4+b/b4HaGsxMTL/Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
