kind: Secret
ansible_user: ENC[AES256_GCM,data:Mco75CifpF0=,iv:JqrwP6UuWy9PlP5vI0Pq84czq2zHEPAMg14UF9r/BhM=,tag:aNGu3YrZhCz1wRRDf8iyfg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zhUC5vHgArnnn2mVDNY=,iv:yiUjwlYRsnTqb6MMMHKtR/JRQssNEaY1jZ++y94oa7c=,tag:67UdEIuWslG8R6DZAFWjWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQlc4N0EwMWFWaXRHRUZO
            SE1ZbllTWk5GMyszV2hBNXVoRkw0U2RScWhRCkRoRmZqclRkS2hta290ZE42RDl5
            VEwyU1RvUTloV2FzS3c3SFZZUzMvS2MKLS0tICtGMWVXQ0lhUEVVVncxSS90aWdQ
            SEJKRnVsVFRLMjdSMnBOTDhNbWJmMlUKHC+kjvqzWNibEVycxFMMdqLxrEkjBO7o
            bjfq0YovaGYjCO4G0guKpn64qnR8wpDBH/YiuIsR2Uf6Yr5jjvfdDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-20T21:15:02Z"
    mac: ENC[AES256_GCM,data:iLyYH3I5WrnfjX1hg1EIwETAIsJRd5g7D9DNa3gdq0HV9ZPpEYPX88/6VfNkQPzlH65g1wEibGPbcwiaqJ2olDEIJrsjI+wKB2zqirIMg1jhMMXef0VMQ5WnNgwShSxytpfVZJlkvRVX4DXYajlt3cvH5M5EdyyNtcK6ftBA7Is=,iv:VpyLOQJraPofzenoB1mVVc4Xe84lM9bipkCF4J535zY=,tag:LNSCwxW8wuloWPNSWI2C5A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
