kind: Secret
ansible_user: ENC[AES256_GCM,data:biBPV7Vbk5I=,iv:RphL6rdK6/qWDlp9PgPWY67kCgm6C5xWExFLxY4hwlc=,tag:aaE2sMxqV95Ut6urGr95vQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Cz/NilTozePusNRtX70=,iv:3f12iyHVNh1n+XAqJC1bQ94CUjg+4AJ/2+hW1W3aLiw=,tag:L7iVxJh6kENxbmkLoSLLTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9t4xcc6dty7v6elh0j3g8dgkz5kpqudyfj49dzapdfjwcq5p32qh2kw55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcjBZYWxqSGhSVFZJdEc5
            ZXdTR2d0KzJ2d3VNWVNUZDN5eWtKSFZwQlRBCmM5RkF3cWlSTmhUMnY2cDV4cGFT
            UWdkMDFmQzBRdzJzWHdOc3l1TEVwZDAKLS0tIHEwZUkza3pueXZ0QmR5dXcwTWIy
            d3NKR09mOVRQVkZLci9hblNzK3dXMk0KqFvrXxzsDH9nelXUYk9WghILKbxmD0pz
            T9cENOd80JI7HBS7TP5ygQJ6Rj1L/XGJ0A7A9ClxcXqSj1Kbw0NUSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-24T00:43:19Z"
    mac: ENC[AES256_GCM,data:uIXOipsihUiyYJq56VyfFzHNJChC6gyTgFW8We4h8YhtLjX+SsyF0E+4Fetd+GX96p+QKW1jrYUfOyCI90UfaCugB5Mz+7ETzMleek/3GlfFYmph4rtvYElNZAwnFRWmXGu/MJ1O1vUN2L5QBgcaa8iWQI+QpnXRqUu3qjcjJC4=,iv:9oV1lnyyiFKG2tDXt5sAp9y1hUHaGl/Fj0kXFx8DJ98=,tag:8aTY5XVKmwnuEmccaeH5jQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
