---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: flux-system
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
