---
creation_rules:
  - path_regex: ./.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      ${BOOTSTRAP_AGE_PUBLIC_KEY}
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      ${BOOTSTRAP_AGE_PUBLIC_KEY}
