kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfsstorage  #fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.37.53
            - name: NFS_PATH
              value: /srv/backup/k8s
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.37.53
            path: /srv/backup/k8s
