---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    image:
      repository: "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner"
      tag: "v4.0.2"
      pullPolicy: IfNotPresent
    nfs:
      server: 192.168.37.53
      path: "/srv/library/k8s"
    storageClass:
      name: nfs-client-external
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
